// <auto-generated />
using System;
using Fiap.Web.InclusivaJobs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.InclusivaJobs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201004910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("INCLUSIVAJOBS")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("VAGAS_SEQ");

            modelBuilder.Entity("Fiap.Web.InclusivaJobs.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ATIVA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_EXPIRACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMPRESA");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<bool>("OfereceAcessibilidade")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("OFERECE_ACESSIBILIDADE");

                    b.Property<int>("QuantidadeVagasPCD")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTIDADE_VAGAS_PCD");

                    b.Property<string>("RecursosAcessibilidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("RECURSOS_ACESSIBILIDADE");

                    b.Property<decimal>("Salario")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("SALARIO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO");

                    b.Property<bool>("VagasPCD")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("VAGAS_PCD");

                    b.HasKey("Id");

                    b.HasIndex("Ativa")
                        .HasDatabaseName("IDX_VAGAS_ATIVA");

                    b.HasIndex("DataExpiracao")
                        .HasDatabaseName("IDX_VAGAS_DATA_EXP");

                    b.HasIndex("VagasPCD")
                        .HasDatabaseName("IDX_VAGAS_PCD");

                    b.ToTable("VAGAS", "INCLUSIVAJOBS");
                });
#pragma warning restore 612, 618
        }
    }
}
